debugging git actions

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -52,13 +52,19 @@ jobs:
     - name: Test with pytest
       run: |
         pytest --doctest-modules pytorch_widedeep --cov-report xml --cov-report term --disable-pytest-warnings --cov=pytorch_widedeep tests/
+    - name: Debug - List files
+      run: |
+        ls -la
+        echo "Content of .coverage file:"
+        cat .coverage || echo ".coverage file not found"
     - name: Upload coverage
       uses: actions/upload-artifact@v4
       with:
-        name: coverage${{ matrix.python-version }}
-        path: coverage-files
+        name: coverage-${{ matrix.python-version }}
+        path: .coverage
+        if-no-files-found: error
 
-  finish: 
+  finish:
     needs: test
     runs-on: ubuntu-latest
     if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
@@ -73,14 +79,15 @@ jobs:
         python -m pip install --upgrade pip
         python -m pip install coverage
     - name: Download all artifacts
-      # Downloads coverage1, coverage2, etc.
       uses: actions/download-artifact@v4
-    - name: List downloaded files
+      with:
+        path: coverage-files
+    - name: Debug - List downloaded files
       run: |
         ls -R coverage-files
     - name: Convert coverage
       run: |
-        coverage combine coverage-files/*/.coverage*
+        coverage combine coverage-files/*/.coverage
         coverage report --fail-under=90
         coverage xml
     - name: upload coverage to Codecov
